# Generated by Django 3.0.5 on 2021-03-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0001_initial'),
        ('threads', '0002_auto_20210310_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='SurfScopeForecast.SurfingInfo'),
        ),
    ]
