# Generated by Django 3.0.5 on 2021-03-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20210310_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
