# Generated by Django 3.0.5 on 2021-04-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField(default='')),
                ('country_name', models.TextField(default='')),
                ('tour_points', models.TextField(default='')),
                ('athlete_country_flag', models.TextField(default='')),
                ('athlete_photo', models.TextField(default='')),
                ('gender', models.TextField(default='')),
            ],
        ),
    ]
