# Generated by Django 3.0.5 on 2021-04-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyleague', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
