# Generated by Django 3.0.5 on 2021-03-11 03:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blackbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=500)),
                ('newfield', models.CharField(default='some string', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SurfingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.TextField(unique=True)),
                ('secretList', jsonfield.fields.JSONField(default='{}')),
                ('fantasyLeague', models.TextField(blank=True)),
                ('alerts', models.TextField(blank=True)),
            ],
        ),
    ]
