# Generated by Django 3.0.5 on 2021-03-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfinginfo',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
