# Generated by Django 3.0.5 on 2021-02-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
