# Generated by Django 2.2.18 on 2021-02-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.TextField()),
                ('secretList', models.TextField()),
                ('fantasyLeague', models.TextField()),
                ('alerts', models.TextField()),
            ],
        ),
    ]
