# Generated by Django 3.0.5 on 2021-03-12 09:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0003_auto_20210312_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfinginfo',
            name='secretList',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
