# Generated by Django 3.0.5 on 2021-02-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0003_surfinginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurfingInfo',
        ),
    ]
