# Generated by Django 3.0.5 on 2021-02-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0004_delete_surfinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.TextField()),
                ('secretList', models.TextField()),
                ('fantasyLeague', models.TextField()),
                ('alerts', models.TextField()),
            ],
        ),
    ]
