# Generated by Django 3.0.5 on 2021-02-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0005_surfinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfinginfo',
            name='ID',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='surfinginfo',
            name='alerts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surfinginfo',
            name='fantasyLeague',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surfinginfo',
            name='secretList',
            field=models.TextField(blank=True),
        ),
    ]
