# Generated by Django 3.1.7 on 2021-04-15 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0008_auto_20210414_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersurdboard',
            old_name='producstUrl',
            new_name='productUrl',
        ),
    ]
