# Generated by Django 3.1.6 on 2021-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurfScopeForecast', '0012_auto_20210219_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.TextField()),
                ('secretList', models.JSONField()),
                ('fantasyLeague', models.TextField()),
                ('alerts', models.TextField()),
            ]),
    ]
