# Generated by Django 3.0.5 on 2021-03-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SurfScopeForecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=2000)),
                ('avatar', models.URLField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=16)),
                ('name', models.CharField(default='', max_length=32)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='SurfScopeForecast.SurfingInfo')),
            ],
        ),
    ]
